DotNet-Frontend/TragInElDotNet/Models/Account.cs
namespace RazorPagesAccount.Models;

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
public class Account {
    public long id {get; set;}
    public long clientId {get; set;}
    public long empId {get; set;}
    public long balance {get; set;}
}

DotNet-Frontend/TragInElDotNet/Models/Client.cs
namespace RazorPagesClient.Models;

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
public class Client {
    public long id {get; set;}
    public string name {get; set;}
    public string surname {get; set;}
    public string npc {get; set;}
    public string phoneNr {get; set;}
}

DotNet-Frontend/TragInElDotNet/Models/Employee.cs
namespace RazorPagesEmployee.Models;

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
public class Employee {
    public long id {get; set;}
    public string name {get; set;}
    public string surname {get; set;}
    public string npc {get; set;}
    public string phoneNr {get; set;}
    public string salary {get; set;}
}

DotNet-Frontend/TragInElDotNet/Pages/Accounts.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using RazorPagesAccount.Models;
using System.Net;
using System.Text;

namespace TragInElDotNet.Pages;

#pragma warning disable CS8601 // Possible null reference assignment.
#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
#pragma warning disable SYSLIB0014 // Type or member is obsolete

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class AccountModel : PageModel
{
    public string url = "http://172.17.0.1:8088/account";
    public List<Account> accounts = new List<Account>();
    private readonly ILogger<AccountModel> _logger;

    public AccountModel(ILogger<AccountModel> logger)
    {
        _logger = logger;
    }

    public async Task OnGet()
    {
        using (var httpClient = new HttpClient())
        {
            using (HttpResponseMessage response = await httpClient.GetAsync(url + "/getAllAccounts"))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                Console.WriteLine(apiResponse);
                this.accounts = JsonConvert.DeserializeObject<List<Account>>(apiResponse);
            }
        }
    }

    public async Task<IActionResult> OnPostAdd(long balance, long angajat_id, long client_id)
    {
        Account ac = new Account();
        ac.balance = balance;
        ac.clientId = angajat_id;
        ac.empId = client_id;

        HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url + "/createAccount");
        httpWebRequest.Method = "POST";
        string json = JsonConvert.SerializeObject(ac);
        byte[] bytearray = Encoding.UTF8.GetBytes(json);
        httpWebRequest.ContentType = "application/json";
        httpWebRequest.ContentLength = bytearray.Length;
        Stream reqStream = httpWebRequest.GetRequestStream();
        reqStream.Write(bytearray, 0, bytearray.Length);
        WebResponse response = httpWebRequest.GetResponse();

        return Redirect("./Accounts");
    }

    public async Task<IActionResult> OnPostModify(int id, long balance, long angajat_id, long client_id)
    {
        if (id != 0)
        {
            Account ac = new Account();
            ac.id = id;
            ac.balance = balance;
            ac.clientId = angajat_id;
            ac.empId = client_id;

            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url + "/modifyAccount");
            httpWebRequest.Method = "POST";
            string json = JsonConvert.SerializeObject(ac);
            byte[] bytearray = Encoding.UTF8.GetBytes(json);
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.ContentLength = bytearray.Length;
            Stream reqStream = httpWebRequest.GetRequestStream();
            reqStream.Write(bytearray, 0, bytearray.Length);
            WebResponse response = httpWebRequest.GetResponse();
        }
        return Redirect("./Accounts");
    }

    public async Task<IActionResult> OnPostDelete(int id)
    {
        if (id != 0)
        {
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url + "/deleteAccount/" + id);
            httpWebRequest.Method = "DELETE";
            WebResponse response = httpWebRequest.GetResponse();
        }
        return Redirect("./Accounts");
    }
}

DotNet-Frontend/TragInElDotNet/Pages/Clients.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using RazorPagesClient.Models;
using System.Net;
using System.Text;

namespace TragInElDotNet.Pages;

#pragma warning disable CS8601 // Possible null reference assignment.
#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
#pragma warning disable SYSLIB0014 // Type or member is obsolete

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ClientModel : PageModel
{
    public string url = "http://172.17.0.1:8088/client";
    public List<Client> clients = new List<Client>();
    private readonly ILogger<ClientModel> _logger;

    public ClientModel(ILogger<ClientModel> logger)
    {
        _logger = logger;
    }

    public async Task OnGet()
    {
        using (var httpClient = new HttpClient())
        {
            using (HttpResponseMessage response = await httpClient.GetAsync(url + "/getAllClients"))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                this.clients = JsonConvert.DeserializeObject<List<Client>>(apiResponse);
            }
        }
    }

    public async Task<IActionResult> OnPostAdd(string name, string surname, string npc, string phoneNr)
    {
        Client cl = new Client();
        cl.name = name;
        cl.surname = surname;
        cl.npc = npc;
        cl.phoneNr = phoneNr;

        HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url + "/createClient");
        httpWebRequest.Method = "POST";
        string json = JsonConvert.SerializeObject(cl);
        byte[] bytearray = Encoding.UTF8.GetBytes(json);
        httpWebRequest.ContentType = "application/json";
        httpWebRequest.ContentLength = bytearray.Length;
        Stream reqStream = httpWebRequest.GetRequestStream();
        reqStream.Write(bytearray, 0, bytearray.Length);
        WebResponse response = httpWebRequest.GetResponse();

        return Redirect("./Clients");
    }

    public async Task<IActionResult> OnPostModify(int id, string name, string surname, string npc, string phoneNr)
    {
        if (id != 0)
        {
            Client cl = new Client();
            cl.id = id;
            cl.name = name;
            cl.surname = surname;
            cl.npc = npc;
            cl.phoneNr = phoneNr;

            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url + "/modifyClient");
            httpWebRequest.Method = "POST";
            string json = JsonConvert.SerializeObject(cl);
            byte[] bytearray = Encoding.UTF8.GetBytes(json);
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.ContentLength = bytearray.Length;
            Stream reqStream = httpWebRequest.GetRequestStream();
            reqStream.Write(bytearray, 0, bytearray.Length);
            WebResponse response = httpWebRequest.GetResponse();
        }
        return Redirect("./Clients");
    }

    public async Task<IActionResult> OnPostDelete(int id)
    {
        if (id != 0)
        {
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url + "/deleteClient/" + id);
            httpWebRequest.Method = "DELETE";
            WebResponse response = httpWebRequest.GetResponse();
        }
        return Redirect("./Clients");
    }
}





DotNet-Frontend/TragInElDotNet/Pages/Employees.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using RazorPagesEmployee.Models;
using System.Net;
using System.Text;

namespace TragInElDotNet.Pages;

#pragma warning disable CS8601 // Possible null reference assignment.
#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
#pragma warning disable SYSLIB0014 // Type or member is obsolete

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class EmployeeModel : PageModel
{
    public string url = "http://172.17.0.1:8088/employee";
    public List<Employee> employees = new List<Employee>();
    private readonly ILogger<EmployeeModel> _logger;

    public EmployeeModel(ILogger<EmployeeModel> logger)
    {
        _logger = logger;
    }

    public async Task OnGet()
    {
        using (var httpClient = new HttpClient())
        {
            using (HttpResponseMessage response = await httpClient.GetAsync(url + "/getAllEmployees"))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                this.employees = JsonConvert.DeserializeObject<List<Employee>>(apiResponse);
            }
        }
    }

    public async Task<IActionResult> OnPostAdd(string name, string surname, string npc, string phoneNr, string salary)
    {
        Employee em = new Employee();
        em.name = name;
        em.surname = surname;
        em.npc = npc;
        em.phoneNr = phoneNr;
        em.salary = salary;

        HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url + "/createEmployee");
        httpWebRequest.Method = "POST";
        string json = JsonConvert.SerializeObject(em);
        byte[] bytearray = Encoding.UTF8.GetBytes(json);
        httpWebRequest.ContentType = "application/json";
        httpWebRequest.ContentLength = bytearray.Length;
        Stream reqStream = httpWebRequest.GetRequestStream();
        reqStream.Write(bytearray, 0, bytearray.Length);
        WebResponse response = httpWebRequest.GetResponse();

        return Redirect("./Employees");
    }

    public async Task<IActionResult> OnPostModify(int id, string name, string surname, string npc, string phoneNr, string salary)
    {
        if (id != 0)
        {
            Employee em = new Employee();
            em.id = id;
            em.name = name;
            em.surname = surname;
            em.npc = npc;
            em.phoneNr = phoneNr;
            em.salary = salary;


            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url + "/modifyEmployee");
            httpWebRequest.Method = "POST";
            string json = JsonConvert.SerializeObject(em);
            byte[] bytearray = Encoding.UTF8.GetBytes(json);
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.ContentLength = bytearray.Length;
            Stream reqStream = httpWebRequest.GetRequestStream();
            reqStream.Write(bytearray, 0, bytearray.Length);
            WebResponse response = httpWebRequest.GetResponse();
        }
        return Redirect("./Employees");
    }

    public async Task<IActionResult> OnPostDelete(int id)
    {
        if (id != 0)
        {
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url + "/deleteEmployee/" + id);
            httpWebRequest.Method = "DELETE";
            WebResponse response = httpWebRequest.GetResponse();
        }
        return Redirect("./Employees");
    }
}

DotNet-Frontend/TragInElDotNet/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TragInElDotNet.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}


DotNet-Frontend/TragInElDotNet/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TragInElDotNet.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        // ViewData["Variable"] = "This is passed from controller.";
    }
}

DotNet-Frontend/TragInElDotNet/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TragInElDotNet.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}


DotNet-Frontend/TragInElDotNet/Pages/Accounts.cshtml
@page
@model TragInElDotNet.Pages.AccountModel
@{
    ViewData["Title"] = "Account page";
}

<style>
    table {
        width: 100%;
        text-align: center;
        font-family: Arial, Helvetica, sans-serif;
        @* border: 1px solid white; *@
        margin-bottom: 8% ;
    }

    .prostii {
        width: 100%;
        text-align: center;
        font-family: Arial, Helvetica, sans-serif;
    }

    .form-class {
        text-align: center;
        width: 100%-6rem fit-content;
        border-radius: 2px;
    @*position:relative;*@font-family: Arial, Helvetica, sans-serif;
        margin-bottom: 3rem;
        min-width: 5rem;
    }

    .tr-header {
        font-weight: bold;
    }

    form {
        @* border: 1px solid white; *@
        margin-bottom: 3 rem;
    }

    tr,
    td {
        border: 1px solid white;
    }
</style>

@using RazorPagesAccount.Models;

<body>
    <div class="prostii">
        <form method="post" class="form-class">
            <p>AddAccount</p>
            <input type="text" name="id" value="" readonly placeholder="Id Not Needed">
            <input type="text" name="client_id" value="" placeholder="Client Id">
            <input type="text" name="angajat_id" value="" placeholder="Employee Id">
            <input type="text" name="balance" value="" placeholder="Balance">
            <button asp-page-handler="Add">Add</button>
        </form>
        <form method="post" class="form-class">
            <p>ModifyAccount</p>
            <input type="text" name="id" value="" placeholder="Id Needed">
            <input type="text" name="client_id" value="" placeholder="Client Id">
            <input type="text" name="angajat_id" value="" placeholder="Employee Id">
            <input type="text" name="balance" value="" placeholder="Balance">
            <button asp-page-handler="Modify">Modify</button>
        </form>

        <form method="post" class="form-class">
            <p>Remove From Existance</p>
            <input type="text" name="id" value="">
            <button asp-page-handler="Delete">Delete</button>
        </form>
    </div>
    @if (Model != null && Model.accounts != null)
    {
        <table>
            <tr class="tr-header">
                <td>Id</td>
                <td>Client Id</td>
                <td>Employee Id</td>
                <td>Balance</td>
            </tr>
            @foreach (Account account in Model.accounts)
            {
                <tr>
                    <td>@account.id</td>
                    <td>@account.clientId</td>
                    <td>@account.empId</td>
                    <td>@account.balance</td>
                </tr>
            }

        </table>
    }
</body>

DotNet-Frontend/TragInElDotNet/Pages/Clients.cshtml
@page
@model TragInElDotNet.Pages.ClientModel
@{
    ViewData["Title"] = "Client page";
}

<style>
    table {
        width: 100%;
        text-align: center;
        font-family: Arial, Helvetica, sans-serif;
        @* border: 1px solid white; *@
        margin-bottom: 8% ;
    }

    .prostii {
        width: 100%;
        text-align: center;
        font-family: Arial, Helvetica, sans-serif;
    }

    .form-class {
        text-align: center;
        width: 100%-6rem fit-content;
        border-radius: 2px;
    @*position:relative;*@font-family: Arial, Helvetica, sans-serif;
        margin-bottom: 3rem;
        min-width: 5rem;
    }

    .tr-header {
        font-weight: bold;
    }

    form {
        @* border: 1px solid white; *@
        margin-bottom: 3 rem;
    }

    tr,
    td {
        border: 1px solid white;
    }
</style>
@using RazorPagesClient.Models;

<body>
    <div class="prostii"></div>
    <form method="post" class="form-class">
        <p>AddClient</p>
        <input type="text" name="id" value="" readonly placeholder="Id Not Needed">
        <input type="text" name="name" value="" placeholder="Client Name">
        <input type="text" name="surname" value="" placeholder="Client Surname">
        <input type="text" name="npc" value="" placeholder="Numeric Personal Code">
        <input type="text" name="phoneNr" value="" placeholder="Phone#">
        <button asp-page-handler="Add">Add</button>
    </form>
    <form method="post" class="form-class">
        <p>ModifyClient</p>
        <input type="text" name="id" value="" placeholder="Id Needed">
        <input type="text" name="name" value="" placeholder="Client Name">
        <input type="text" name="surname" value="" placeholder="Client Surname">
        <input type="text" name="npc" value="" placeholder="Numeric Personal Code">
        <input type="text" name="phoneNr" value="" placeholder="Phone#">
        <button asp-page-handler="Modify">Modify</button>
    </form>

    <form method="post" class="form-class">
        <p>Remove From Existance</p>
        <input type="text" name="id" value="">
        <button asp-page-handler="Delete">Delete</button>
    </form>
    </div>
    @if (Model != null && Model.clients != null)
    {
        <table>
            <tr class="tr-header">
                <td>Id</td>
                <td>Name</td>
                <td>Surname</td>
                <td>NPC</td>
                <td>Phone#</td>
            </tr>
            @foreach (Client client in Model.clients)
            {
                <tr>
                    <td>@client.id</td>
                    <td>@client.name</td>
                    <td>@client.surname</td>
                    <td>@client.npc</td>
                    <td>@client.phoneNr</td>
                </tr>
            }

        </table>
    }
</body>

DotNet-Frontend/TragInElDotNet/Pages/Employees.cshtml
@page
@model TragInElDotNet.Pages.EmployeeModel
@{
    ViewData["Title"] = "Employee page";
}

<style>
    table {
        width: 100%;
        text-align: center;
        font-family: Arial, Helvetica, sans-serif;
        @* border: 1px solid white; *@
        margin-bottom: 8% ;
    }

    .prostii {
        width: 100%;
        text-align: center;
        font-family: Arial, Helvetica, sans-serif;
    }

    .form-class {
        text-align: center;
        width: 100%-6rem fit-content;
        border-radius: 2px;
    @*position:relative;*@font-family: Arial, Helvetica, sans-serif;
        margin-bottom: 3rem;
        min-width: 5rem;
    }

    .tr-header {
        font-weight: bold;
    }

    form {
        @* border: 1px solid white; *@
        margin-bottom: 3 rem;
    }

    tr,
    td {
        border: 1px solid white;
    }
</style>
@using RazorPagesEmployee.Models;

<body>
    <div class="prostii">
        <form method="post" class="form-class">
            <p>AddEmployee</p>
            <input type="text" name="id" value="" readonly placeholder="Id Not Needed">
            <input type="text" name="name" value="" placeholder="Employee Name">
            <input type="text" name="surname" value="" placeholder="Employee Surname">
            <input type="text" name="npc" value="" placeholder="Numeric Personal Code">
            <input type="text" name="phoneNr" value="" placeholder="Phone#">
            <input type="text" name="salary" value="" placeholder="Salary">
            <button asp-page-handler="Add">Add</button>
        </form>
        <form method="post" class="form-class">
            <p>ModifyEmployee</p>
            <input type="text" name="id" value="" placeholder="Id Needed">
            <input type="text" name="name" value="" placeholder="Employee Name">
            <input type="text" name="surname" value="" placeholder="Employee Surname">
            <input type="text" name="npc" value="" placeholder="Numeric Personal Code">
            <input type="text" name="phoneNr" value="" placeholder="Phone#">
            <input type="text" name="salary" value="" placeholder="Salary">
            <button asp-page-handler="Modify">Modify</button>
        </form>

        <form method="post" class="form-class">
            <p>Remove From Existance</p>
            <input type="text" name="id" value="">
            <button asp-page-handler="Delete">Delete</button>
        </form>
    </div>
    @if (Model != null && Model.employees != null)
    {
        <table>
            <tr class="tr-header">
                <td>Id</td>
                <td>Name</td>
                <td>Surname</td>
                <td>NPC</td>
                <td>Phone#</td>
                <td>Salary</td>
            </tr>
            @foreach (Employee employee in Model.employees)
            {
                <tr>
                    <td>@employee.id</td>
                    <td>@employee.name</td>
                    <td>@employee.surname</td>
                    <td>@employee.npc</td>
                    <td>@employee.phoneNr</td>
                    <td>@employee.salary</td>
                </tr>
            }

        </table>
    }
</body>

DotNet-Frontend/TragInElDotNet/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    @* var variable = ViewData["Variable"]; *@
}

<div class="text-dark">
    <h1 class="display-4">Welcome</h1>
    <h3>General information</h3>

    <img src="https://static-00.iconduck.com/assets.00/dotnet-icon-512x512-1rx2815d.png" width="150px" height="150px">
    <img src="https://i.pinimg.com/originals/36/fd/a1/36fda1085cffacaebc7613ab8f227351.png" width="150px"
        height="150px">
    <img src="https://pngimg.com/uploads/mysql/mysql_PNG23.png" width="150px" height="150px">
    <img src="https://www.fileeagle.com/data/2015/08/HeidiSQL.png" width="150px" height="150px">
    <img src="https://alternative.me/media/256/apache-maven-icon-kh9tgmmob2lmuoko-c.png" height="150px">

    <p>This is a client web-application running on .NET which communicates with a Maven Spring backend.</p>
    <p>Technologies used in the backend includes (but not limited to):</p>
    <ul>
        <li>SpringBoot;</li>
        <li>JpaRepository;</li>
        <li>Microservices.</li>
    </ul>
    <br>

    <h3>SQL</h3>
    <p>The Java backend manages a HeidiSQL(MariaDB/MySQL server) with the following tables:</p>
    <ul>
        <li>Account;</li>
        <li>Employee;</li>
        <li>Client;</li>
        <li>User.</li>
    </ul>
    <p>These tables contain primary keys for their id (which has different names from table to table). The only table
        with foreign keys is the Account table. It contains four columns (id, client id, employee id and balance) to
        which client id and employee id are foreign keys to the primary keys in Client and Employee tables.</p>
    <p></p>

    <h3>Microservices</h3>
    <p>The microservices technology in this application uses the Model-View-Controller architecture on top of
        SpringBoot, together with Maven.</p>
    <p>
        In this project. There are 4 model classes as mentioned above (Client, Account, User, Employee) using standard
        &#64;Entity annotations together with some logic regarding table names, primary keys and auto-increment of id.
    </p>
    <p>The 4 repositories that make use of the model classes mentioned above extend JpaRepository and make use of their
        pre-defined queries to get the information from the tables.
    </p>

    <p>There is a service for each of the aforementioned repositories in which the custom logic resides. Here there is
        some checking regarding the modification and creation of new entries in the DB.</p>
</div>